# Generated by Django 4.1.7 on 2024-06-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_alter_profilemodel_followers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="following", to="profiles.profilemodel"
            ),
        ),
    ]
